name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ startsWith(github.event.commits[0].message, '[release]') }}
      SNAPSHOT: ${{ startsWith(github.event.commits[0].message, '[snapshot]') }}
      MAVEN_TYPE: ${{ env.RELEASE && 'releases' || 'snapshots'  }} # this is a ternary?? Who designed this syntax
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: build
        # only run when not a release or snapshot
        if: ${{ !env.SNAPSHOT && !env.RELEASE }}
        run: ./gradlew build

      - name: publish
        # when publishing a release or snapshot, do this instead of build.
        if: ${{ env.SNAPSHOT || env.RELEASE }}
        # build task creates artifacts for capture and upload, then publish publishes to maven
        run: ./gradlew build publish

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: publish to Modrinth and Curseforge
        # only publish to MR and CF when releasing
        if: ${{ env.RELEASE }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: tEJPA4Ty
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 696251
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-featured: false # leave it to auto featuring

          changelog-file: CHANGELOG.txt

          loaders: |
            fabric
            quilt

          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}

      - name: prepare for next release
        if: ${{ env.RELEASE }}
        run: ./gradlew postRelease

      - name: push updated version and changelog
        if: ${{ env.RELEASE }}
        run: |
          git add .
          git commit -m "Clean changelog and bump version"
          git push
