name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: ./gradlew build

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
