name: release
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      MAVEN_TYPE: releases
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    outputs:
      version: ${{ steps.publish.outputs.version }}
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: publish
        id: publish
        run: ./gradlew publish grabVersion # grabVersion stores the version in a special file that GitHub will read

      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/

      - name: publish to Modrinth and Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: tEJPA4Ty
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 696251
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-featured: false # leave it to auto featuring

          name: ${{ steps.publish.outputs.version }}
          version: ${{ steps.publish.outputs.version }}

          loaders: |
            fabric
            quilt

          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}
