name: Snapshot
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNAPSHOT: 'true'
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Publish
        # build task creates artifacts for capture and upload, then publish publishes to maven
        run: ./gradlew build publish

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
